# Generated by Django 5.0.1 on 2024-02-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrix_integration', '0002_alter_result_date_alter_result_hole_diff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='par',
        ),
    ]
